on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Build container image
      run: docker build . --file Dockerfile --tag hugomd/hugo-base-image:${GITHUB_SHA:0:8} --tag hugomd/hugo-base-image:latest

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Push image to Docker Hub
      run: docker push hugomd/hugo-base-image
